# Generated by Django 5.2.16 on 2026-07-16 18:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='題目')),
                ('question_type', models.CharField(choices=[('desmos', 'Desmos 數學輸入'), ('multiple_choice', '選擇題')], max_length=30, verbose_name='題型')),
                ('correct_answer', models.CharField(blank=True, max_length=255, verbose_name='正確答案')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='題集名稱')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='選項文字')),
                ('value', models.CharField(max_length=100, verbose_name='儲存值')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.questionset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questionset',
            name='questions',
            field=models.ManyToManyField(through='assessments.QuestionSetItem', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120, verbose_name='學生姓名')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.questionset')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='作答內容')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.submission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionsetitem',
            constraint=models.UniqueConstraint(fields=('question_set', 'question'), name='unique_question_in_set'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='one_answer_per_question'),
        ),
    ]
